Repository limo-sum/anser, pull requests merged in 2020-09, with the labels that each got.

#43 modify: import 라이브러리 순서대로 재 조정
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  src/Pages/Components/CRSP/StepFour.js
  src/Pages/Components/CRSP/StepOne.js
  src/Pages/SignUp/Signup.js
  src/config.js
Labels: Status: 리뷰 요청

#44 Refactor: API 추가
  public/data/savedqueries.json
  public/data/userData.json
  src/Pages/Components/CRSP/StepThreeContents.js
  src/Pages/SavedQueries/SavedQueries.js
  src/Pages/SignIn/SignIn.js
  src/Pages/SignUp/Signup.js
  src/Pages/UserInfo/AccountInfo.js
  src/config.js
  src/redux/reducers/loginReducers.js
Labels: Status: 리뷰 요청

#45 Refactor: API 주소 수정
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/TableData.js
  src/config.js
Labels: Status: Accept

#49 Fix: 로그인 시 상단 nav 바뀌지않던 오류 수정
  src/Components/Nav/Header/Header.js
  src/Components/Nav/Logout.js
  src/Components/Nav/MainNav.js
  src/Components/Nav/Nav.js
  src/config.js
Labels: Status: Accept

#50 Fix: Query 오류 해결
  public/data/crsptab.json
  src/Pages/Components/Main/LatestNews.js
  src/Pages/Components/Main/PageHighlight.js
  src/Pages/SavedQueries/SavedQueries.js
  src/Pages/SignIn/SignIn.js
Labels: Status: 수정 요청

#51 Fix: Add to code list 부분 수정
  public/data/searchData.json
  src/Pages/Components/CRSP/CodeLookup.js
  src/config.js
Labels: Status: Accept

#53 Fix: stock code 저장하게 수정
  src/Pages/Components/CRSP/CodeLookup.js
Labels: Status: 리뷰 요청

#54 Modify: identifier 버튼 삭제
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/TableData.js
Labels: Status: 리뷰 요청

#60 Fix: 회원 정보 날짜 형식 수정
  src/Components/Nav/TopPanel.js
  src/Pages/UserInfo/AccountInfo.js
Labels: Status: Accept

#63 Add: CardList Page 및 SavedQueries Checkbox 추가
  public/data/cardList.json
  src/Pages/CRSP.js
  src/Pages/CardPage/Card.js
  src/Pages/CardPage/CardPage.js
  src/Pages/CardPage/CardPageRoute.js
  src/Pages/Components/CRSP/StepThreeContents.js
  src/Pages/Components/Main/ContactMap.js
  src/Pages/Components/Main/DataVenders.js
  src/Pages/Components/Main/LatestNews.js
  src/Pages/Components/Main/PageHighlight.js
  src/Pages/Components/Main/Testinominals.js
  src/Pages/Main/Main.js
  src/Pages/SavedQueries/EachQueries.js
  src/Pages/SavedQueries/SavedQueries.js
  src/Pages/SignUp/Signup.js
  src/Pages/SignUp/Verification.js
  src/Routes.js
Labels: Status: 수정 요청

#61 add: 다운로드 기능완성 쓸모없어진 리캡차 제거
  package-lock.json
  package.json
  public/Images/HYU_LOGO.png
  public/Images/HYU_initial_kor.png
  src/Components/Footer/Footer.js
  src/Pages/Components/CRSP/StepFour.js
  src/Pages/SignUp/Signup.js
  src/config.js
Labels: Status: 추가 기능 구현중

#65 Refactor: Verification 버튼 위치 조정
  public/data/querytemp.json
  src/Pages/SavedQueries/EachQueries.js
  src/Pages/SavedQueries/SavedQueries.js
  src/Pages/SignUp/Signup.js
  src/Pages/SignUp/Verification.js
Labels: Status: 수정 요청

#62 Fix: Top panel 수정
  public/Images/tplus.jpg
  public/data/topPanelLogin.json
  src/Components/Nav/Header/Header.js
  src/Components/Nav/MainNav.js
  src/Components/Nav/TopPanel.js
  src/Components/Nav/TopPanelLoginData.js
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/StepFour.js
  src/Pages/Components/CRSP/TableData.js
  src/redux/reducers/loginReducers.js
Labels: Status: Accept

#68 Add: Main CRSP 추가
  public/Images/chart.jpeg
  src/Pages/CRSP.js
  src/Pages/CardPage/Card.js
  src/Pages/CardPage/CardPage.js
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/Main/SmallCRSP.js
  src/Pages/Components/Main/SmallTableData.js
  src/Pages/Components/Main/SomethingHere.js
  src/Pages/Main/Main.js
  src/Pages/SavedQueries/EachQueries.js
  src/Pages/SavedQueries/SavedQueries.js
  src/Pages/SignUp/Signup.js
Labels: Status: 수정 요청

#66 Add: loading spinner 추가
  public/Images/loading2.gif
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/StepFour.js
  src/Pages/Components/Main/ContactMap.js
  src/Pages/SignIn/SignIn.js
Labels: Status: 수정 요청
