Repository limo-sum/anser, pull requests merged in 2020-08, with the labels that each got.

#13 Add: KAKAO LOGIN
  public/Images/google_logo.png
  public/Images/kakao_login.png
  public/index.html
  src/Pages/SignIn.js
Labels: Status: 수정 요청

#19 Fix: 오류 수정
  package-lock.json
  src/Components/Nav/Nav.js
  src/Pages/Components/Main/ContactMap.js
  src/Pages/Components/Main/ContactUs.js
  src/Pages/Components/Main/DataVenders.js
  src/Pages/Components/Main/LatestNews.js
  src/Pages/Components/Main/PageHighlight.js
  src/Pages/Components/Main/Testinominals.js
  src/Pages/Main/Main.js
  src/Pages/SignIn/SignIn.js
  src/Pages/SignUp/Signup.js
  src/Pages/UserInfo/AccountInfo.js
  src/Routes.js
Labels: Status: 리뷰 요청

#18 Add: CRSP Sidebar Layout
  package-lock.json
  package.json
  public/Images/main.jpeg
  public/data/crsptab.json
  public/index.html
  src/Pages/CRSP.js
  src/Pages/Components/CRSP/StepThree.js
  src/Pages/Main/Main.js
  src/Routes.js
Labels: Status: 수정 요청

#17 Refactor: 코드 리뷰에 따른 재재수정
  src/Components/Footer/Footer.js
  src/Pages/SignUp/Signup.js
  src/config.js
Labels: Status: 수정 요청

#21 Add: 구글 소셜 로그인 기능 추가
  public/Images/HYU_symbol_basic_png.png
  public/Images/hyu_typo_logo.png
  public/index.html
  src/Components/Nav/Header/Header.js
  src/Components/Nav/Login.js
  src/Components/Nav/Logout.js
  src/Components/Nav/MainNav.js
  src/Components/Nav/Nav.js
  src/Pages/SignIn/GoogleLogin.js
  src/Pages/SignIn/SignIn.js
  src/Pages/SignUp/Signup.js
  src/config.js
Labels: Status: 리뷰 요청

#22 add: CRSP Step1 완성
  src/Pages/CRSP.js
  src/Pages/Components/CRSP/StepOne.js
Labels: Status: 리뷰 요청

#23 Add: 1차 레이아웃 완료
  .env
  src/Pages/CRSP.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/StepThree.js
Labels: Status: Accept

#24 Add: StepThree Layout
  package-lock.json
  package.json
  public/data/crsptab.json
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/StepThree.js
  src/Pages/Components/CRSP/StepThreeSelect.js
  src/Pages/Components/CRSP/StepThreeSelected.js
Labels: Status: 수정 요청

#26 Add: Search 기능 1차 완료
  .gitignore
  public/Images/loading.gif
  public/data/searchData.json
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/SecondModalBody.js
  src/config.js
Labels: Status: Accept

#28 Feature/step three structure
  public/data/crsptab.json
  public/data/stepThreeCategory.json
  src/Pages/Components/CRSP/StepThree.js
  src/Pages/Components/CRSP/StepThreeContents.js
  src/Pages/Components/CRSP/StepThreeSelect.js
  src/Pages/Components/CRSP/StepThreeSelected.js
  src/config.js
Labels: Status: 리뷰 요청

#29 Add: SavedQueries Page Layout 완성
  public/data/savedqueries.json
  src/Pages/Components/CRSP/StepThreeContents.js
  src/Pages/SavedQueries/SavedQueries.js
  src/Routes.js
Labels: Status: 리뷰 요청

#30 Add: 엑셀 다운로드 기능 추가
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  package-lock.json
  package.json
  public/data/searchData.json
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/CodeLookupText.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/SecondModal.js
  src/Pages/Components/CRSP/TableData.js
  src/Styles/ModalStyle.js
Labels: Status: Accept

#31 Refactor: 드롭다운 메뉴 리스트 일부 삭제
  public/data/tabitems.json
  src/Components/Nav/MainNav.js
  src/Components/Nav/Nav.js
  src/Components/Nav/TopPanelLoginData.js
  src/config.js
Labels: Status: 리뷰 요청

#25 add: step4 레이아웃 완성
  public/data/inputlist.json
  public/data/inputlistrequire.json
  src/Pages/CRSP.js
  src/Pages/Components/CRSP/StepFour.js
  src/Pages/Components/CRSP/StepOne.js
  src/Pages/SignUp/Signup.js
  src/config.js
Labels: Status: 추가 기능 구현중

#33 Add: 탭 추가
  src/Pages/CRSP.js
Labels: Status: 리뷰 요청

#34 Fix: GoogleMap 오류 수정
  public/data/crsptab.json
  public/index.html
  src/Pages/Components/CRSP/StepThreeSelect.js
  src/Pages/Components/Main/ContactMap.js
  src/Pages/Components/Main/ContactUs.js
  src/Pages/UserInfo/AccountInfo.js
Labels: Status: 수정 요청

#35 Modify: 모달창 크기 수정
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/SecondModal.js
  src/Styles/ModalStyle.js
  src/Styles/reset.css
  src/Styles/style.js
Labels: Status: Accept

#36 Fix: 링크 태그 오동작 수정
  src/Components/Nav/MainNav.js
  src/Components/Nav/Nav.js
Labels: Status: Accept

#37 Refactor: sessionStorage 추가 함수
  public/data/stepThreeCategory.json
  src/Pages/Components/CRSP/StepThreeContents.js
  src/Pages/Components/CRSP/StepThreeSelect.js
  src/Pages/Components/CRSP/StepThreeSelected.js
  src/Pages/Components/Main/ContactMap.js
  src/Styles/style.js
Labels: Status: 수정 요청

#38 Fix: GoogleMap 오류 수정
  public/index.html
  src/Pages/Components/CRSP/StepThreeContents.js
  src/Pages/Components/Main/ContactMap.js
  src/Pages/Components/Main/ContactUs.js
  src/Pages/Main/Main.js
  src/Pages/SavedQueries/SavedQueries.js
Labels: Status: 수정 요청

#39 Add: session storage 저장 함수 추가
  src/Pages/CRSP.js
  src/Pages/Components/CRSP/CodeLookup.js
  src/Pages/Components/CRSP/Search.js
  src/Pages/Components/CRSP/StepOne.js
  src/Pages/Components/CRSP/TableData.js
Labels: Status: Accept

#40 Refactor: AccountInfo Data 변경
  public/data/userData.json
  src/Pages/SavedQueries/SavedQueries.js
  src/Pages/UserInfo/AccountInfo.js
Labels: Status: Accept

#41 fix: 마우스 이벤트 오류 해결
  package-lock.json
  package.json
  src/Components/Footer/Footer.js
  src/Pages/CRSP.js
  src/Pages/Components/CRSP/StepFour.js
  src/Pages/Components/CRSP/StepOne.js
  src/Pages/SignUp/Signup.js
Labels: Status: 수정 요청
